// @generated by backend/scripts/export_contracts.py; DO NOT EDIT MANUALLY.
// Source of truth: backend/app/schemas (Pydantic v2).

export const CONTRACT_SCHEMA_VERSION = "2.0.0" as const;

export type ContractAgentCapability = "supervisor" | "diagnosis" | "retrieval" | "planning" | "rules" | "approval" | "skill" | "assessment" | "report";

export type ContractAgentDecisionSource = "agent_suggestion" | "deterministic_rule" | "human_decision";

/**
 * Auditable decision summary without exposing prompts or hidden reasoning.
 */
export type ContractAgentDecisionSummary = {
  schema_version?: string;
  entity_version?: number;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  risk_level?: ContractRiskLevel;
  confidence?: number | null;
  trace_id?: string | null;
  request_id?: string | null;
  idempotency_key?: string | null;
  metadata?: {
  [key: string]: unknown;
};
  id: string;
  status?: "recorded";
  run_id: string;
  title: string;
  summary: string;
  evidence_ids?: Array<string>;
  source: ContractAgentDecisionSource;
};

export type ContractAgentEventType = "agent_stage_changed" | "skill_started" | "skill_succeeded" | "skill_failed" | "rule_blocked" | "approval_required" | "approval_decided" | "plan_replanned" | "run_retried" | "run_rolled_back" | "human_takeover_required" | "run_completed" | "run_failed";

/**
 * Typed payload for Agent progress events.
 */
export type ContractAgentProgressPayload = {
  schema_version?: string;
  entity_version?: number;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  risk_level?: ContractRiskLevel;
  confidence?: number | null;
  trace_id?: string | null;
  request_id?: string | null;
  idempotency_key?: string | null;
  metadata?: {
  [key: string]: unknown;
};
  id: string;
  status: ContractAgentStepStatus;
  run_id: string;
  step_id: string;
  progress_percent: number;
  summary: string;
  checkpoint_id?: string | null;
  retry_count?: number;
  formal_write_occurred?: boolean;
};

/**
 * Top-level traceable Agent execution for a training task.
 */
export type ContractAgentRun = {
  schema_version?: string;
  entity_version?: number;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  risk_level?: ContractRiskLevel;
  confidence?: number | null;
  trace_id?: string | null;
  request_id?: string | null;
  idempotency_key?: string | null;
  metadata?: {
  [key: string]: unknown;
};
  id: string;
  status: ContractAgentRunStatus;
  task_id: string;
  state: ContractAgentState;
  steps?: Array<ContractAgentStepSummary>;
  decisions?: Array<ContractAgentDecisionSummary>;
  current_stage: string;
};

/**
 * Agent execution states from chapter 15.8.
 */
export type ContractAgentRunStatus = "AR-PENDING" | "AR-RUNNING" | "AR-WAIT-INPUT" | "AR-WAIT-APPROVAL" | "AR-WAIT-EXTERNAL" | "AR-RETRYING" | "AR-ROLLING-BACK" | "AR-REPLANNING" | "AR-PAUSED" | "AR-MANUAL" | "AR-SUCCEEDED" | "AR-FAILED" | "AR-CANCELLED";

/**
 * Serializable resumable Agent state, distinct from an API envelope or event.
 */
export type ContractAgentState = {
  schema_version?: string;
  entity_version?: number;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  risk_level?: ContractRiskLevel;
  confidence?: number | null;
  trace_id?: string | null;
  request_id?: string | null;
  idempotency_key?: string | null;
  metadata?: {
  [key: string]: unknown;
};
  id: string;
  status: ContractAgentRunStatus;
  task_id: string;
  current_step_id?: string | null;
  current_plan_id?: string | null;
  current_approval_id?: string | null;
  checkpoint_id?: string | null;
  retry_count?: number;
  waiting_for?: string | null;
  recoverable?: boolean;
  formal_write_occurred?: boolean;
};

export type ContractAgentStateResponse = {
  schema_version?: string;
  request_id: string;
  trace_id: string;
  occurred_at: string;
  data: ContractAgentState;
};

export type ContractAgentStepStatus = "pending" | "running" | "waiting" | "succeeded" | "failed" | "skipped";

/**
 * Auditable summary for one Agent execution step.
 */
export type ContractAgentStepSummary = {
  schema_version?: string;
  entity_version?: number;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  risk_level?: ContractRiskLevel;
  confidence?: number | null;
  trace_id?: string | null;
  request_id?: string | null;
  idempotency_key?: string | null;
  metadata?: {
  [key: string]: unknown;
};
  id: string;
  status: ContractAgentStepStatus;
  run_id: string;
  capability: ContractAgentCapability;
  label: string;
  input_summary: string;
  output_summary?: string;
  decision_reason?: string | null;
  checkpoint_id?: string | null;
  retry_count?: number;
  writes_committed?: boolean;
  model_name?: string | null;
  prompt_version?: string | null;
  token_count?: number | null;
  latency_ms?: number | null;
  skill_name?: string | null;
  error_code?: string | null;
  started_at?: string | null;
  finished_at?: string | null;
};

/**
 * Common response envelope fields; concrete responses add a typed data field.
 */
export type ContractApiEnvelope = {
  schema_version?: string;
  request_id: string;
  trace_id: string;
  occurred_at: string;
};

/**
 * Human approval record for high-risk or otherwise gated writes.
 */
export type ContractApproval = {
  schema_version?: string;
  entity_version?: number;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  risk_level?: ContractRiskLevel;
  confidence?: number | null;
  trace_id?: string | null;
  request_id?: string | null;
  idempotency_key?: string | null;
  metadata?: {
  [key: string]: unknown;
};
  id: string;
  status: ContractApprovalStatus;
  task_id: string;
  plan_id: string;
  requested_by: string;
  reviewer_role_id: string;
  reviewer_id?: string | null;
  risk_summary: string;
  impact_scope: Array<string>;
  knowledge_citation_ids?: Array<string>;
  submitted_at?: string | null;
  decided_at?: string | null;
  decision?: ContractApprovalDecision | null;
  decision_comment?: string | null;
  requested_changes?: Array<string>;
};

export type ContractApprovalDecision = "approved" | "approved_with_changes" | "rejected" | "returned_for_information";

/**
 * Minimal, permission-safe approval event payload.
 */
export type ContractApprovalEventPayload = {
  schema_version?: string;
  entity_version?: number;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  risk_level?: ContractRiskLevel;
  confidence?: number | null;
  trace_id?: string | null;
  request_id?: string | null;
  idempotency_key?: string | null;
  metadata?: {
  [key: string]: unknown;
};
  id: string;
  status: ContractApprovalStatus;
  run_id: string;
  approval_id: string;
  summary: string;
};

/**
 * Concise result emitted after an approval action.
 */
export type ContractApprovalResult = {
  schema_version?: string;
  entity_version?: number;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  risk_level?: ContractRiskLevel;
  confidence?: number | null;
  trace_id?: string | null;
  request_id?: string | null;
  idempotency_key?: string | null;
  metadata?: {
  [key: string]: unknown;
};
  id: string;
  status: ContractApprovalStatus;
  task_id: string;
  plan_id: string;
  reviewer_id: string;
  decision: ContractApprovalDecision;
  decision_comment?: string | null;
  decided_at: string;
};

export type ContractApprovalResultResponse = {
  schema_version?: string;
  request_id: string;
  trace_id: string;
  occurred_at: string;
  data: ContractApprovalResult;
};

/**
 * Approval states from chapter 15.8.
 */
export type ContractApprovalStatus = "AP-NOT-SUBMITTED" | "AP-WAITING" | "AP-EDITING" | "AP-APPROVED" | "AP-REJECTED" | "AP-WITHDRAWN" | "AP-EXPIRED" | "AP-CANCELLED";

export type ContractAssessmentDraftView = {
  schema_version?: string;
  task_id: string;
  attempt: number;
  answers: {
  [key: string]: Array<number>;
};
  saved_at: string;
  storage: "local" | "synced";
};

export type ContractAssessmentNextAction = "complete" | "remediation" | "human_review";

/**
 * Scorable question bound to one governed knowledge point.
 */
export type ContractAssessmentQuestion = {
  schema_version?: string;
  entity_version?: number;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  risk_level: ContractRiskLevel;
  confidence?: number | null;
  trace_id?: string | null;
  request_id?: string | null;
  idempotency_key?: string | null;
  metadata?: {
  [key: string]: unknown;
};
  id: string;
  status?: "active";
  question_type: ContractAssessmentQuestionType;
  prompt: string;
  options: Array<string>;
  correct_option_indexes: Array<number>;
  knowledge_point_id: string;
  knowledge_point_name: string;
};

export type ContractAssessmentQuestionType = "single" | "multiple" | "boolean";

/**
 * Scored assessment result; never a direct performance or HR conclusion.
 */
export type ContractAssessmentResult = {
  schema_version?: string;
  entity_version?: number;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  risk_level?: ContractRiskLevel;
  confidence?: number | null;
  trace_id?: string | null;
  request_id?: string | null;
  idempotency_key?: string | null;
  metadata?: {
  [key: string]: unknown;
};
  id: string;
  status: "scored";
  assessment_session_id: string;
  task_id: string;
  employee_profile_id: string;
  score_percent: number;
  passed: boolean;
  high_risk_passed: boolean;
  knowledge_point_performances?: Array<ContractKnowledgePointPerformance>;
  next_action: ContractAssessmentNextAction;
  scored_at: string;
  disclaimer?: string;
};

export type ContractAssessmentResultResponse = {
  schema_version?: string;
  request_id: string;
  trace_id: string;
  occurred_at: string;
  data: ContractAssessmentResult;
};

export type ContractAssessmentResultView = {
  schema_version?: string;
  id: string;
  assessment_session_id: string;
  task_id: string;
  employee_profile_id: string;
  attempt: number;
  score_percent: number;
  passed: boolean;
  high_risk_passed: boolean;
  knowledge_point_performances?: Array<ContractKnowledgePointPerformance>;
  next_action: ContractAssessmentNextAction;
  submitted_at: string;
  previous_score_percent?: number | null;
  score_change_percent?: number | null;
  wrong_answer_reasons?: Array<ContractWrongAnswerReason>;
  disclaimer: string;
};

/**
 * One employee's one assessment attempt for a training task.
 */
export type ContractAssessmentSession = {
  schema_version?: string;
  entity_version?: number;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  risk_level?: ContractRiskLevel;
  confidence?: number | null;
  trace_id?: string | null;
  request_id?: string | null;
  idempotency_key?: string | null;
  metadata?: {
  [key: string]: unknown;
};
  id: string;
  status: ContractAssessmentSessionStatus;
  task_id: string;
  employee_profile_id: string;
  attempt: number;
  started_at?: string | null;
  submitted_at?: string | null;
};

export type ContractAssessmentSessionStatus = "pending" | "in_progress" | "submitted" | "scored" | "cancelled";

/**
 * Reusable learning course bound to authorized knowledge points.
 */
export type ContractCourse = {
  schema_version?: string;
  entity_version?: number;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  risk_level?: ContractRiskLevel;
  confidence?: number | null;
  trace_id?: string | null;
  request_id?: string | null;
  idempotency_key?: string | null;
  metadata?: {
  [key: string]: unknown;
};
  id: string;
  status: ContractCourseStatus;
  title: string;
  department_ids?: Array<string>;
  knowledge_point_ids?: Array<string>;
  duration_minutes: number;
  required?: boolean;
};

export type ContractCourseDetailView = {
  schema_version?: string;
  task_id: string;
  title: string;
  units: Array<ContractCourseUnitContent>;
  current_unit_index: number;
  content_version: string;
  is_remedial?: boolean;
};

/**
 * Course projection embedded in a training-plan read response.
 */
export type ContractCoursePlanItem = {
  schema_version?: string;
  id: string;
  title: string;
  department_name: string;
  duration_minutes: number;
  risk_level: ContractRiskLevel;
  completed?: boolean;
  knowledge_point_ids?: Array<string>;
};

export type ContractCourseStatus = "draft" | "active" | "retired";

export type ContractCourseUnitContent = {
  schema_version?: string;
  id: string;
  title: string;
  duration_minutes: number;
  risk_level: ContractRiskLevel;
  completed?: boolean;
  eyebrow: string;
  heading: string;
  paragraphs: Array<string>;
  key_points: Array<string>;
  scenario_question: string;
  scenario_answer: string;
  knowledge_citation_ids?: Array<string>;
};

export type ContractCreateTrainingTaskInput = {
  training_goal_id: string;
  name: string;
  objective: string;
  target_department_ids?: Array<string>;
  target_employee_profile_ids?: Array<string>;
  deadline: string;
};

export type ContractCreateTrainingTaskRequest = {
  schema_version?: string;
  request_id: string;
  idempotency_key: string;
  actor_id: string;
  data: ContractCreateTrainingTaskInput;
};

export type ContractCreateTrainingTaskResponse = {
  schema_version?: string;
  request_id: string;
  trace_id: string;
  occurred_at: string;
  data: ContractTrainingTask;
};

/**
 * Organization department node.
 */
export type ContractDepartment = {
  schema_version?: string;
  entity_version?: number;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  risk_level?: ContractRiskLevel;
  confidence?: number | null;
  trace_id?: string | null;
  request_id?: string | null;
  idempotency_key?: string | null;
  metadata?: {
  [key: string]: unknown;
};
  id: string;
  status: ContractEntityStatus;
  name: string;
  parent_department_id?: string | null;
};

/**
 * Dify-style structured output example backed by the same Pydantic schema.
 */
export type ContractDifyPlanAgentOutput = {
  schema_version?: string;
  training_goal_id: string;
  proposed_plan_id: string;
  title: string;
  summary: string;
  selection_reason: string;
  course_ids: Array<string>;
  knowledge_citation_ids?: Array<string>;
  risk_level: ContractRiskLevel;
  confidence: number;
  human_review_required: boolean;
  warnings?: Array<string>;
};

/**
 * Training-oriented employee profile with a minimal authorized data scope.
 */
export type ContractEmployeeProfile = {
  schema_version?: string;
  entity_version?: number;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  risk_level?: ContractRiskLevel;
  confidence?: number | null;
  trace_id?: string | null;
  request_id?: string | null;
  idempotency_key?: string | null;
  metadata?: {
  [key: string]: unknown;
};
  id: string;
  status: ContractEntityStatus;
  user_id: string;
  department_id: string;
  job_title: string;
  training_tags?: Array<string>;
  authorized_data_scopes?: Array<string>;
};

export type ContractEntityStatus = "active" | "inactive" | "archived";

export type ContractErrorCategory = "validation" | "permission_scope" | "state_conflict" | "knowledge_version" | "approval_required" | "agent_failure" | "skill_failure" | "external_failure" | "retry_exhausted" | "manual_takeover" | "internal";

export type ContractErrorCode = "INVALID_INPUT" | "MISSING_INFORMATION" | "UNAUTHORIZED" | "FORBIDDEN_SCOPE" | "STATE_CONFLICT" | "APPROVAL_REQUIRED" | "APPROVAL_REJECTED" | "APPROVAL_EXPIRED" | "KNOWLEDGE_NOT_FOUND" | "KNOWLEDGE_VERSION_CONFLICT" | "IDEMPOTENCY_CONFLICT" | "AGENT_FAILED" | "SKILL_FAILED" | "CONNECTOR_TIMEOUT" | "CONNECTOR_UNAVAILABLE" | "EXTERNAL_RESULT_UNKNOWN" | "RETRY_LIMIT_REACHED" | "MANUAL_TAKEOVER_REQUIRED" | "INTERNAL_ERROR";

/**
 * Minimal error event payload without stack, prompt, secret, or private data.
 */
export type ContractErrorEventPayload = {
  schema_version?: string;
  entity_version?: number;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  risk_level?: ContractRiskLevel;
  confidence?: number | null;
  trace_id?: string | null;
  request_id?: string | null;
  idempotency_key?: string | null;
  metadata?: {
  [key: string]: unknown;
};
  id: string;
  status?: "failed";
  run_id: string;
  error_id: string;
  code: string;
  retryable: boolean;
  summary: string;
};

export type ContractErrorResponse = {
  schema_version?: string;
  request_id: string;
  trace_id: string;
  occurred_at: string;
  error: ContractUnifiedError;
};

/**
 * Field-level validation problem safe for a caller to display.
 */
export type ContractFieldError = {
  field: string;
  code: string;
  message: string;
};

export type ContractGoalStatus = "draft" | "active" | "completed" | "cancelled";

/**
 * Traceable citation to an authorized enterprise knowledge snapshot.
 */
export type ContractKnowledgeCitation = {
  schema_version?: string;
  entity_version?: number;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  risk_level?: ContractRiskLevel;
  confidence?: number | null;
  trace_id?: string | null;
  request_id?: string | null;
  idempotency_key?: string | null;
  metadata?: {
  [key: string]: unknown;
};
  id: string;
  status: ContractKnowledgeValidity;
  document_name: string;
  document_version: string;
  source_department_id?: string | null;
  section: string;
  excerpt: string;
  relation: string;
  retrieved_at: string;
  content_hash: string;
  authorized_scopes?: Array<string>;
};

/**
 * Assessment performance for one knowledge point.
 */
export type ContractKnowledgePointPerformance = {
  schema_version?: string;
  entity_version?: number;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  risk_level: ContractRiskLevel;
  confidence?: number | null;
  trace_id?: string | null;
  request_id?: string | null;
  idempotency_key?: string | null;
  metadata?: {
  [key: string]: unknown;
};
  id: string;
  status: ContractLearningRecordStatus;
  assessment_session_id: string;
  knowledge_point_id: string;
  knowledge_point_name: string;
  score_percent: number;
  passed: boolean;
  reason: string;
};

export type ContractKnowledgeValidity = "effective" | "conflict" | "expired" | "revoked";

export type ContractLearningProgressView = {
  schema_version?: string;
  task: ContractTrainingTaskView;
  current_unit_index: number;
  saved_at: string;
  attempt?: number | null;
};

/**
 * Employee learning states from chapter 15.8.
 */
export type ContractLearningRecordStatus = "LR-PENDING" | "LR-LEARNING" | "LR-WAIT-ASSESSMENT" | "LR-NOT-MET" | "LR-REMEDIAL" | "LR-WAIT-RETEST" | "LR-RETESTING" | "LR-COMPLETED" | "LR-PAUSED";

export type ContractNotificationDestination = "task" | "assessment" | "remedial";

export type ContractNotificationItemView = {
  schema_version?: string;
  id: string;
  title: string;
  description: string;
  created_at: string;
  icon: string;
  unread: boolean;
  task_id?: string | null;
  destination?: ContractNotificationDestination | null;
};

export type ContractPlanGenerationInput = {
  training_goal_id: string;
  task_id: string;
  required_course_ids?: Array<string>;
  constraints?: Array<string>;
  candidate_count?: number;
};

export type ContractPlanGenerationRequest = {
  schema_version?: string;
  request_id: string;
  trace_id: string;
  idempotency_key: string;
  actor_id: string;
  data: ContractPlanGenerationInput;
};

export type ContractPlanGenerationResponse = {
  schema_version?: string;
  request_id: string;
  trace_id: string;
  occurred_at: string;
  run_id: string;
  data: Array<ContractTrainingPlan>;
};

export type ContractPlanStatus = "draft" | "candidate" | "confirmed" | "superseded";

/**
 * Permission-safe signed-in user projection for prototype clients.
 */
export type ContractPrototypeUserProfile = {
  schema_version?: string;
  user_id: string;
  employee_profile_id?: string | null;
  display_name: string;
  role: ContractUserRole;
  department_name: string;
  job_title: string;
  account_label?: string | null;
};

/**
 * Ordered realtime event envelope for Web/Android progress updates.
 */
export type ContractRealtimeEvent = {
  schema_version?: string;
  entity_version?: number;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  risk_level?: ContractRiskLevel;
  confidence?: number | null;
  trace_id?: string | null;
  request_id?: string | null;
  idempotency_key?: string | null;
  metadata?: {
  [key: string]: unknown;
};
  id: string;
  status?: "emitted";
  event_type: ContractAgentEventType;
  occurred_at: string;
  run_id: string;
  task_id: string;
  sequence: number;
  payload: ContractAgentProgressPayload | ContractApprovalEventPayload | ContractErrorEventPayload;
};

export type ContractRealtimeEventResponse = {
  schema_version?: string;
  request_id: string;
  trace_id: string;
  occurred_at: string;
  data: ContractRealtimeEvent;
};

export type ContractRemedialPlanView = {
  schema_version?: string;
  task_id: string;
  title: string;
  reason: string;
  weak_points: Array<ContractWeakKnowledgePoint>;
  requirements: Array<string>;
  next_step: string;
  current_step: 1 | 2 | 3;
};

/**
 * Targeted follow-up learning created from an assessment result.
 */
export type ContractRemediationIntervention = {
  schema_version?: string;
  entity_version?: number;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  risk_level?: ContractRiskLevel;
  confidence?: number | null;
  trace_id?: string | null;
  request_id?: string | null;
  idempotency_key?: string | null;
  metadata?: {
  [key: string]: unknown;
};
  id: string;
  status: ContractRemediationStatus;
  task_id: string;
  assessment_result_id: string;
  employee_profile_id: string;
  weak_knowledge_point_ids: Array<string>;
  required_course_ids?: Array<string>;
  reason: string;
  attempt: number;
  completed_at?: string | null;
};

export type ContractRemediationResultResponse = {
  schema_version?: string;
  request_id: string;
  trace_id: string;
  occurred_at: string;
  data: ContractRemediationIntervention;
};

export type ContractRemediationStatus = "planned" | "in_progress" | "completed" | "manual" | "cancelled";

export type ContractReportStatus = "draft" | "awaiting_confirmation" | "confirmed";

export type ContractReportSummary = {
  schema_version?: string;
  task_id: string;
  completion_rate_percent: number;
  assessment_pass_rate_percent: number;
  remedial_count: number;
  reassessment_count: number;
  high_risk_intervention_count: number;
  status: ContractReportStatus;
  disclaimer: string;
};

/**
 * Retest scheduled after a remediation intervention.
 */
export type ContractRetest = {
  schema_version?: string;
  entity_version?: number;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  risk_level?: ContractRiskLevel;
  confidence?: number | null;
  trace_id?: string | null;
  request_id?: string | null;
  idempotency_key?: string | null;
  metadata?: {
  [key: string]: unknown;
};
  id: string;
  status: ContractRetestStatus;
  remediation_id: string;
  task_id: string;
  employee_profile_id: string;
  assessment_session_id?: string | null;
  result_id?: string | null;
  scheduled_at?: string | null;
  completed_at?: string | null;
};

export type ContractRetestResultResponse = {
  schema_version?: string;
  request_id: string;
  trace_id: string;
  occurred_at: string;
  data: ContractRetest;
};

export type ContractRetestStatus = "waiting" | "in_progress" | "completed" | "manual" | "cancelled";

/**
 * Risk grading aligned with the document's read-only/low/medium/high levels.
 */
export type ContractRiskLevel = "read_only" | "low" | "medium" | "high";

/**
 * Role and permission-scope reference; it does not replace the permission engine.
 */
export type ContractRole = {
  schema_version?: string;
  entity_version?: number;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  risk_level?: ContractRiskLevel;
  confidence?: number | null;
  trace_id?: string | null;
  request_id?: string | null;
  idempotency_key?: string | null;
  metadata?: {
  [key: string]: unknown;
};
  id: string;
  status: ContractEntityStatus;
  role_code: ContractUserRole;
  name: string;
  permission_scopes?: Array<string>;
};

export type ContractRuleCheckResult = "passed" | "warning" | "blocked";

/**
 * Deterministic rule result referenced by a plan or task.
 */
export type ContractRuleCheckSummary = {
  schema_version?: string;
  entity_version?: number;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  risk_level?: ContractRiskLevel;
  confidence?: number | null;
  trace_id?: string | null;
  request_id?: string | null;
  idempotency_key?: string | null;
  metadata?: {
  [key: string]: unknown;
};
  id: string;
  status: ContractRuleCheckResult;
  rule_code: string;
  label: string;
  detail: string;
  deterministic?: boolean;
};

export type ContractSubmitApprovalInput = {
  task_id: string;
  plan_id: string;
  reviewer_role_id: string;
  risk_summary: string;
  impact_scope: Array<string>;
  knowledge_citation_ids?: Array<string>;
};

export type ContractSubmitApprovalRequest = {
  schema_version?: string;
  request_id: string;
  idempotency_key: string;
  actor_id: string;
  data: ContractSubmitApprovalInput;
};

/**
 * Training objective and its audience/constraint boundary.
 */
export type ContractTrainingGoal = {
  schema_version?: string;
  entity_version?: number;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  risk_level?: ContractRiskLevel;
  confidence?: number | null;
  trace_id?: string | null;
  request_id?: string | null;
  idempotency_key?: string | null;
  metadata?: {
  [key: string]: unknown;
};
  id: string;
  status: ContractGoalStatus;
  title: string;
  objective: string;
  target_department_ids?: Array<string>;
  target_employee_profile_ids?: Array<string>;
  mandatory_requirements?: Array<string>;
  high_risk_requirements?: Array<string>;
  deadline?: string | null;
};

/**
 * Versioned candidate or confirmed plan for one training goal.
 */
export type ContractTrainingPlan = {
  schema_version?: string;
  entity_version?: number;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  risk_level?: ContractRiskLevel;
  confidence?: number | null;
  trace_id?: string | null;
  request_id?: string | null;
  idempotency_key?: string | null;
  metadata?: {
  [key: string]: unknown;
};
  id: string;
  status: ContractPlanStatus;
  training_goal_id: string;
  title: string;
  candidate_label: string;
  summary: string;
  selection_reason: string;
  course_ids: Array<string>;
  knowledge_citation_ids?: Array<string>;
  rule_checks?: Array<ContractRuleCheckSummary>;
  approval_id?: string | null;
};

/**
 * Training-plan read model with its already-authorized embedded resources.
 */
export type ContractTrainingPlanDetail = {
  schema_version?: string;
  entity_version?: number;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  risk_level?: ContractRiskLevel;
  confidence?: number | null;
  trace_id?: string | null;
  request_id?: string | null;
  idempotency_key?: string | null;
  metadata?: {
  [key: string]: unknown;
};
  id: string;
  status: ContractPlanStatus;
  training_goal_id: string;
  title: string;
  candidate_label: string;
  summary: string;
  selection_reason: string;
  course_ids: Array<string>;
  knowledge_citation_ids?: Array<string>;
  rule_checks?: Array<ContractRuleCheckSummary>;
  approval_id?: string | null;
  target_department_names?: Array<string>;
  courses: Array<ContractCoursePlanItem>;
  knowledge_citations?: Array<ContractKnowledgeCitation>;
};

export type ContractTrainingRecordView = {
  schema_version?: string;
  task_id: string;
  task_name: string;
  learning_status: ContractLearningRecordStatus;
  completed_at?: string | null;
  result_summary: string;
};

/**
 * Executable training assignment governed by chapter 15 business states.
 */
export type ContractTrainingTask = {
  schema_version?: string;
  entity_version?: number;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  risk_level?: ContractRiskLevel;
  confidence?: number | null;
  trace_id?: string | null;
  request_id?: string | null;
  idempotency_key?: string | null;
  metadata?: {
  [key: string]: unknown;
};
  id: string;
  status: ContractTrainingTaskStatus;
  training_goal_id: string;
  current_plan_id?: string | null;
  name: string;
  objective: string;
  target_department_ids?: Array<string>;
  target_employee_profile_ids?: Array<string>;
  deadline: string;
  progress_percent?: number;
  approval_id?: string | null;
};

/**
 * Training business states from chapter 15.8.
 */
export type ContractTrainingTaskStatus = "TB-DRAFT" | "TB-NEED-INPUT" | "TB-ANALYZING" | "TB-PLAN-READY" | "TB-WAIT-CONFIRM" | "TB-WAIT-APPROVAL" | "TB-APPROVAL-EDIT" | "TB-APPROVAL-REJECTED" | "TB-WAIT-PUBLISH" | "TB-IN-PROGRESS" | "TB-COMPLETED" | "TB-FAILED" | "TB-PAUSED" | "TB-MANUAL" | "TB-CANCELLED";

/**
 * Direct client read contract with task and employee-learning states separated.
 */
export type ContractTrainingTaskView = {
  schema_version?: string;
  id: string;
  training_goal_id: string;
  task_status: ContractTrainingTaskStatus;
  learning_status: ContractLearningRecordStatus;
  current_plan_id?: string | null;
  approval_id?: string | null;
  name: string;
  objective: string;
  department_name: string;
  audience_label: string;
  department_names?: Array<string>;
  audience_labels?: Array<string>;
  mandatory_requirements?: Array<string>;
  high_risk_requirements?: Array<string>;
  deadline: string;
  risk_level: ContractRiskLevel;
  progress_percent: number;
  estimated_minutes: number;
  next_action_label: string;
  availability_reason?: string | null;
  created_at: string;
};

export type ContractTutorAnswerKind = "supported" | "refused" | "manual";

export type ContractTutorAnswerView = {
  schema_version?: string;
  id: string;
  answer: string;
  kind: ContractTutorAnswerKind;
  knowledge_citation_ids?: Array<string>;
  high_risk_notice?: string | null;
};

export type ContractTutorSessionView = {
  schema_version?: string;
  welcome: string;
  suggestions?: Array<string>;
};

/**
 * Unified external error object with no secret, stack, prompt, or unauthorized data.
 */
export type ContractUnifiedError = {
  error_id: string;
  code: ContractErrorCode;
  message: string;
  category: ContractErrorCategory;
  retryable: boolean;
  user_action?: string | null;
  details?: {
  [key: string]: unknown;
};
  field_errors?: Array<ContractFieldError>;
  trace_id: string;
  occurred_at: string;
  schema_version?: string;
};

/**
 * Application user identity without credential or sensitive HR fields.
 */
export type ContractUser = {
  schema_version?: string;
  entity_version?: number;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
  updated_by?: string | null;
  risk_level?: ContractRiskLevel;
  confidence?: number | null;
  trace_id?: string | null;
  request_id?: string | null;
  idempotency_key?: string | null;
  metadata?: {
  [key: string]: unknown;
};
  id: string;
  status: ContractEntityStatus;
  display_name: string;
  role_ids: Array<string>;
  department_ids?: Array<string>;
};

export type ContractUserRole = "employee" | "training_admin" | "reviewer" | "system_admin";

export type ContractWeakKnowledgePoint = {
  knowledge_point_id: string;
  knowledge_point_name: string;
  reason: string;
  risk_level: ContractRiskLevel;
};

export type ContractWrongAnswerReason = {
  question_id: string;
  knowledge_point_id: string;
  knowledge_point_name: string;
  reason: string;
  recommendation: string;
};

export const CONTRACT_MODEL_NAMES = [
  "ApiEnvelope",
  "User",
  "Role",
  "Department",
  "EmployeeProfile",
  "TrainingGoal",
  "TrainingTask",
  "TrainingPlan",
  "Course",
  "RuleCheckSummary",
  "KnowledgeCitation",
  "Approval",
  "ApprovalResult",
  "AssessmentSession",
  "AssessmentQuestion",
  "AssessmentResult",
  "KnowledgePointPerformance",
  "RemediationIntervention",
  "Retest",
  "AgentRun",
  "AgentDecisionSummary",
  "AgentState",
  "AgentStepSummary",
  "AgentProgressPayload",
  "ApprovalEventPayload",
  "ErrorEventPayload",
  "RealtimeEvent",
  "FieldError",
  "UnifiedError",
  "CreateTrainingTaskInput",
  "CreateTrainingTaskRequest",
  "CreateTrainingTaskResponse",
  "PlanGenerationInput",
  "PlanGenerationRequest",
  "PlanGenerationResponse",
  "SubmitApprovalInput",
  "SubmitApprovalRequest",
  "ApprovalResultResponse",
  "AssessmentResultResponse",
  "RemediationResultResponse",
  "RetestResultResponse",
  "AgentStateResponse",
  "RealtimeEventResponse",
  "ErrorResponse",
  "DifyPlanAgentOutput",
  "PrototypeUserProfile",
  "CoursePlanItem",
  "TrainingPlanDetail",
  "TrainingTaskView",
  "TrainingRecordView",
  "CourseUnitContent",
  "CourseDetailView",
  "LearningProgressView",
  "TutorSessionView",
  "TutorAnswerView",
  "WrongAnswerReason",
  "AssessmentResultView",
  "AssessmentDraftView",
  "WeakKnowledgePoint",
  "RemedialPlanView",
  "NotificationItemView",
  "ReportSummary"
] as const;
export type ContractModelName = (typeof CONTRACT_MODEL_NAMES)[number];
