// Generated by C-07. Do not edit by hand; run pnpm data:generate -- --profile small.

import type {
  ContractAgentRun,
  ContractApproval,
  ContractAssessmentQuestion,
  ContractKnowledgeCitation,
  ContractPrototypeUserProfile,
  ContractReportSummary,
  ContractTrainingPlanDetail,
  ContractTrainingTaskView
} from "@tegang/types";

export const contractIds = {
  "adminUser": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
  "approval": "approval_01M049ANR0CF7H24E47X21FD95",
  "completedTask": "task_01M046F4230GE74AMHC0E01DSH",
  "courseBase": "course_01M044J2Y023VMY1V94VNHSTNR",
  "courseIt": "course_01M044J2Y2J1WWKKYBE4ZFSTGG",
  "courseRemedial": "course_01M044J2Y3Z4EP6KJ8RYMR2AWC",
  "courseSteel": "course_01M044J2Y10Q50YCY7AWRAM8DV",
  "employeeProfile": "emp_01ARZ3NDEKTSV4RRFFQ69G5FAV",
  "employeeUser": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAV",
  "goal": "goal_01M045GKG0YKARB9345NMT6ZDM",
  "knowBase": "know_01M041PH80E4V8HF66N5YZ15VE",
  "knowIt": "know_01M041PH8293AC5R0HCXN7JX43",
  "knowSteel": "know_01M041PH81FPGX0Z1HX3MC4QPR",
  "kpBase": "kp_01M042N1T0APS81540KBJJB9GF",
  "kpIt": "kp_01M042N1T2BXMMQ4E3KRKST5MF",
  "kpSteel": "kp_01M042N1T1TS8PDWBQY7BTJN1H",
  "planA": "plan_01M047DMM0ACV9QPS6XFC9QZWN",
  "planB": "plan_01M047DMM10WDYXV6ZW4QWA2PY",
  "reviewerRole": "role_01ARZ3NDEKTSV4RRFFQ69G5FAX",
  "reviewerUser": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAX",
  "run": "run_01M04F1S40VCRAWFDR55R14CBZ",
  "systemUser": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAY",
  "task": "task_01M046F420RT87AVTSH37F903B",
  "trace": "trc_01M04M6QE8D6RM4DR5EN7XK7Y6"
} as const;

export const demoUsers: ContractPrototypeUserProfile[] = [
  {
    "account_label": "E-0231",
    "department_name": "炼钢生产部",
    "display_name": "模拟员工 E-0231",
    "employee_profile_id": "emp_01ARZ3NDEKTSV4RRFFQ69G5FAV",
    "job_title": "炼钢生产岗位（模拟）",
    "role": "employee",
    "schema_version": "2.2.0",
    "user_id": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAV"
  },
  {
    "account_label": "A-001",
    "department_name": "培训管理",
    "display_name": "模拟培训管理员 A-001",
    "employee_profile_id": "emp_01ARZ3NDEKTSV4RRFFQ69G5FAW",
    "job_title": "培训管理员岗位（模拟）",
    "role": "training_admin",
    "schema_version": "2.2.0",
    "user_id": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW"
  },
  {
    "account_label": "R-001",
    "department_name": "安全管理",
    "display_name": "模拟审核员 R-001",
    "employee_profile_id": "emp_01ARZ3NDEKTSV4RRFFQ69G5FAX",
    "job_title": "安全审核岗位（模拟）",
    "role": "reviewer",
    "schema_version": "2.2.0",
    "user_id": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAX"
  },
  {
    "account_label": "S-001",
    "department_name": "智信部",
    "display_name": "模拟系统管理员 S-001",
    "employee_profile_id": "emp_01ARZ3NDEKTSV4RRFFQ69G5FAY",
    "job_title": "系统管理员岗位（模拟）",
    "role": "system_admin",
    "schema_version": "2.2.0",
    "user_id": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAY"
  }
];

export const knowledgeCitations: ContractKnowledgeCitation[] = [
  {
    "authorized_scopes": [
      "training:read",
      "department:dept_01ARZ3NDEKTSV4RRFFQ69G5FAV"
    ],
    "confidence": null,
    "content_hash": "sha256:892a2bbba733f4441266c77a25b2a20f3c0fe179d664e2e90feead5981bbb9d0",
    "created_at": "2026-08-17T00:00:00Z",
    "created_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
    "document_name": "《生产区域基础行为模拟培训说明 01》",
    "document_version": "SIM-1.0.0-1",
    "entity_version": 1,
    "excerpt": "生产区域基础行为相关内容仅用于验证授权检索、引用和风险提示。",
    "id": "know_01M041PH80E4V8HF66N5YZ15VE",
    "idempotency_key": null,
    "metadata": {
      "dataset_version": "1.0.0",
      "profile": "small",
      "simulated": true
    },
    "relation": "支撑模拟培训方案、题目和测评关系校验。",
    "request_id": "req_01M04MVY50S3Z13SKATCKTCJ34",
    "retrieved_at": "2026-08-17T00:00:00Z",
    "risk_level": "medium",
    "schema_version": "2.2.0",
    "section": "模拟要求",
    "source_department_id": "dept_01ARZ3NDEKTSV4RRFFQ69G5FAV",
    "status": "effective",
    "trace_id": "trc_01M04KXDK0F26DJRFCSJR9X57B",
    "updated_at": "2026-08-17T00:05:00Z",
    "updated_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW"
  },
  {
    "authorized_scopes": [
      "training:read",
      "department:dept_01ARZ3NDEKTSV4RRFFQ69G5FAW"
    ],
    "confidence": null,
    "content_hash": "sha256:ef21f5819be63af3109ec2321156138a94a2a0d9867be35d780eff39e7e1be2f",
    "created_at": "2026-08-17T00:01:00Z",
    "created_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
    "document_name": "《高温区域进入前确认模拟培训说明 02》",
    "document_version": "SIM-1.0.0-1",
    "entity_version": 1,
    "excerpt": "高温区域进入前确认相关内容仅用于验证授权检索、引用和风险提示。",
    "id": "know_01M041PH81FPGX0Z1HX3MC4QPR",
    "idempotency_key": null,
    "metadata": {
      "dataset_version": "1.0.0",
      "profile": "small",
      "simulated": true
    },
    "relation": "支撑模拟培训方案、题目和测评关系校验。",
    "request_id": "req_01M04MVY5154PS3EBZFYW6BZK0",
    "retrieved_at": "2026-08-17T00:01:00Z",
    "risk_level": "high",
    "schema_version": "2.2.0",
    "section": "模拟要求",
    "source_department_id": "dept_01ARZ3NDEKTSV4RRFFQ69G5FAW",
    "status": "effective",
    "trace_id": "trc_01M04KXDK1RV3QHRJHC2RVDQ0K",
    "updated_at": "2026-08-17T00:06:00Z",
    "updated_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW"
  },
  {
    "authorized_scopes": [
      "training:read",
      "department:dept_01ARZ3NDEKTSV4RRFFQ69G5FAX"
    ],
    "confidence": null,
    "content_hash": "sha256:7e690dfb737dce3420d12cb7c1e2994fdacf46582d2a2cab816e28c9e8a6e2ee",
    "created_at": "2026-08-17T00:02:00Z",
    "created_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
    "document_name": "《设备联锁与隔离边界模拟培训说明 03》",
    "document_version": "SIM-1.0.0-1",
    "entity_version": 1,
    "excerpt": "设备联锁与隔离边界相关内容仅用于验证授权检索、引用和风险提示。",
    "id": "know_01M041PH8293AC5R0HCXN7JX43",
    "idempotency_key": null,
    "metadata": {
      "dataset_version": "1.0.0",
      "profile": "small",
      "simulated": true
    },
    "relation": "支撑模拟培训方案、题目和测评关系校验。",
    "request_id": "req_01M04MVY525CN94ZK3RRD6YM6A",
    "retrieved_at": "2026-08-17T00:02:00Z",
    "risk_level": "high",
    "schema_version": "2.2.0",
    "section": "模拟要求",
    "source_department_id": "dept_01ARZ3NDEKTSV4RRFFQ69G5FAX",
    "status": "effective",
    "trace_id": "trc_01M04KXDK2MDNF2C10DVXNEXQR",
    "updated_at": "2026-08-17T00:07:00Z",
    "updated_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW"
  }
];

export const trainingTask: ContractTrainingTaskView = {
  "approval_id": "approval_01M049ANR0CF7H24E47X21FD95",
  "audience_label": "四部门模拟参训员工",
  "audience_labels": [
    "炼钢生产部模拟员工",
    "培训管理模拟员工",
    "安全管理模拟员工",
    "智信部模拟员工"
  ],
  "availability_reason": null,
  "created_at": "2026-08-18T03:20:00Z",
  "current_plan_id": "plan_01M047DMM10WDYXV6ZW4QWA2PY",
  "deadline": "2026-09-30",
  "department_name": "炼钢生产部",
  "department_names": [
    "炼钢生产部",
    "培训管理",
    "安全管理",
    "智信部"
  ],
  "estimated_minutes": 90,
  "high_risk_requirements": [
    "高风险知识点独立达标"
  ],
  "id": "task_01M046F420RT87AVTSH37F903B",
  "learning_status": "LR-LEARNING",
  "mandatory_requirements": [
    "基础制度",
    "部门知识",
    "测评留痕"
  ],
  "name": "新员工高风险安全规范与岗位基础培训（模拟）",
  "next_action_label": "继续学习",
  "objective": "验证基础制度、部门知识、高风险审批、测评、补训和复测闭环。",
  "progress_percent": 42.0,
  "risk_level": "high",
  "schema_version": "2.2.0",
  "task_status": "TB-WAIT-CONFIRM",
  "training_goal_id": "goal_01M045GKG0YKARB9345NMT6ZDM"
};

export const candidatePlans: ContractTrainingPlanDetail[] = [
  {
    "approval_id": null,
    "candidate_label": "候选 A",
    "confidence": null,
    "course_ids": [
      "course_01M044J2Y023VMY1V94VNHSTNR",
      "course_01M044J2Y10Q50YCY7AWRAM8DV",
      "course_01M044J2Y2J1WWKKYBE4ZFSTGG"
    ],
    "courses": [
      {
        "completed": true,
        "department_name": "炼钢生产部",
        "duration_minutes": 20,
        "id": "course_01M044J2Y023VMY1V94VNHSTNR",
        "knowledge_point_ids": [
          "kp_01M042N1T0APS81540KBJJB9GF",
          "kp_01M042N1T1TS8PDWBQY7BTJN1H",
          "kp_01M042N1T2BXMMQ4E3KRKST5MF",
          "kp_01M042N1T34GQ3GK4CSQ57XV5B",
          "kp_01M042N1T41QJVRVC188STV0XP"
        ],
        "risk_level": "medium",
        "schema_version": "2.2.0",
        "title": "模拟课程 001：受控培训与风险边界"
      },
      {
        "completed": false,
        "department_name": "培训管理",
        "duration_minutes": 30,
        "id": "course_01M044J2Y10Q50YCY7AWRAM8DV",
        "knowledge_point_ids": [
          "kp_01M042N1T5AZ4HHPYJ41XHNXVR",
          "kp_01M042N1T6PKFX6FZHWYW5M6TN",
          "kp_01M042N1T7F0VJR4XXCPGVEENK",
          "kp_01M042N1T8GMDGYMEPT26WT6QM",
          "kp_01M042N1T9SRC3GFVT69FTC1JA"
        ],
        "risk_level": "high",
        "schema_version": "2.2.0",
        "title": "模拟课程 002：受控培训与风险边界"
      },
      {
        "completed": false,
        "department_name": "安全管理",
        "duration_minutes": 40,
        "id": "course_01M044J2Y2J1WWKKYBE4ZFSTGG",
        "knowledge_point_ids": [
          "kp_01M042N1TAAV1DMQFGF72FS2HF",
          "kp_01M042N1TB9QQK6TT3HMG3HS0D",
          "kp_01M042N1TCYQRSCQ2946A35XHV",
          "kp_01M042N1TDJZV44RNH3W4SZDAT",
          "kp_01M042N1TE005Y8BV8BP1SJBC7"
        ],
        "risk_level": "medium",
        "schema_version": "2.2.0",
        "title": "模拟课程 003：受控培训与风险边界"
      }
    ],
    "created_at": "2026-08-18T10:00:00Z",
    "created_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
    "entity_version": 1,
    "id": "plan_01M047DMM0ACV9QPS6XFC9QZWN",
    "idempotency_key": null,
    "knowledge_citation_ids": [
      "know_01M041PH80E4V8HF66N5YZ15VE",
      "know_01M041PH81FPGX0Z1HX3MC4QPR",
      "know_01M041PH8293AC5R0HCXN7JX43"
    ],
    "knowledge_citations": [
      {
        "authorized_scopes": [
          "training:read",
          "department:dept_01ARZ3NDEKTSV4RRFFQ69G5FAV"
        ],
        "confidence": null,
        "content_hash": "sha256:892a2bbba733f4441266c77a25b2a20f3c0fe179d664e2e90feead5981bbb9d0",
        "created_at": "2026-08-17T00:00:00Z",
        "created_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
        "document_name": "《生产区域基础行为模拟培训说明 01》",
        "document_version": "SIM-1.0.0-1",
        "entity_version": 1,
        "excerpt": "生产区域基础行为相关内容仅用于验证授权检索、引用和风险提示。",
        "id": "know_01M041PH80E4V8HF66N5YZ15VE",
        "idempotency_key": null,
        "metadata": {
          "dataset_version": "1.0.0",
          "profile": "small",
          "simulated": true
        },
        "relation": "支撑模拟培训方案、题目和测评关系校验。",
        "request_id": "req_01M04MVY50S3Z13SKATCKTCJ34",
        "retrieved_at": "2026-08-17T00:00:00Z",
        "risk_level": "medium",
        "schema_version": "2.2.0",
        "section": "模拟要求",
        "source_department_id": "dept_01ARZ3NDEKTSV4RRFFQ69G5FAV",
        "status": "effective",
        "trace_id": "trc_01M04KXDK0F26DJRFCSJR9X57B",
        "updated_at": "2026-08-17T00:05:00Z",
        "updated_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW"
      },
      {
        "authorized_scopes": [
          "training:read",
          "department:dept_01ARZ3NDEKTSV4RRFFQ69G5FAW"
        ],
        "confidence": null,
        "content_hash": "sha256:ef21f5819be63af3109ec2321156138a94a2a0d9867be35d780eff39e7e1be2f",
        "created_at": "2026-08-17T00:01:00Z",
        "created_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
        "document_name": "《高温区域进入前确认模拟培训说明 02》",
        "document_version": "SIM-1.0.0-1",
        "entity_version": 1,
        "excerpt": "高温区域进入前确认相关内容仅用于验证授权检索、引用和风险提示。",
        "id": "know_01M041PH81FPGX0Z1HX3MC4QPR",
        "idempotency_key": null,
        "metadata": {
          "dataset_version": "1.0.0",
          "profile": "small",
          "simulated": true
        },
        "relation": "支撑模拟培训方案、题目和测评关系校验。",
        "request_id": "req_01M04MVY5154PS3EBZFYW6BZK0",
        "retrieved_at": "2026-08-17T00:01:00Z",
        "risk_level": "high",
        "schema_version": "2.2.0",
        "section": "模拟要求",
        "source_department_id": "dept_01ARZ3NDEKTSV4RRFFQ69G5FAW",
        "status": "effective",
        "trace_id": "trc_01M04KXDK1RV3QHRJHC2RVDQ0K",
        "updated_at": "2026-08-17T00:06:00Z",
        "updated_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW"
      },
      {
        "authorized_scopes": [
          "training:read",
          "department:dept_01ARZ3NDEKTSV4RRFFQ69G5FAX"
        ],
        "confidence": null,
        "content_hash": "sha256:7e690dfb737dce3420d12cb7c1e2994fdacf46582d2a2cab816e28c9e8a6e2ee",
        "created_at": "2026-08-17T00:02:00Z",
        "created_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
        "document_name": "《设备联锁与隔离边界模拟培训说明 03》",
        "document_version": "SIM-1.0.0-1",
        "entity_version": 1,
        "excerpt": "设备联锁与隔离边界相关内容仅用于验证授权检索、引用和风险提示。",
        "id": "know_01M041PH8293AC5R0HCXN7JX43",
        "idempotency_key": null,
        "metadata": {
          "dataset_version": "1.0.0",
          "profile": "small",
          "simulated": true
        },
        "relation": "支撑模拟培训方案、题目和测评关系校验。",
        "request_id": "req_01M04MVY525CN94ZK3RRD6YM6A",
        "retrieved_at": "2026-08-17T00:02:00Z",
        "risk_level": "high",
        "schema_version": "2.2.0",
        "section": "模拟要求",
        "source_department_id": "dept_01ARZ3NDEKTSV4RRFFQ69G5FAX",
        "status": "effective",
        "trace_id": "trc_01M04KXDK2MDNF2C10DVXNEXQR",
        "updated_at": "2026-08-17T00:07:00Z",
        "updated_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW"
      }
    ],
    "metadata": {
      "dataset_version": "1.0.0",
      "profile": "small",
      "simulated": true
    },
    "request_id": "req_01M04MZ0CRFPHRH6CA980JG6A4",
    "risk_level": "medium",
    "rule_checks": [
      {
        "confidence": null,
        "created_at": "2026-08-18T08:20:00Z",
        "created_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
        "detail": "必修课程和部门路径完整。",
        "deterministic": true,
        "entity_version": 1,
        "id": "rule_01M048C5607HW8FWR5JN6JA2TP",
        "idempotency_key": null,
        "label": "必修内容完整",
        "metadata": {
          "dataset_version": "1.0.0",
          "profile": "small",
          "simulated": true
        },
        "request_id": "req_01M04MZ09MZHV8D35DQGQ9MGJY",
        "risk_level": "medium",
        "rule_code": "MANDATORY_CONTENT_COMPLETE",
        "schema_version": "2.2.0",
        "status": "passed",
        "trace_id": "trc_01M04M0FQM197KSGB81QDMMYCM",
        "updated_at": "2026-08-18T08:25:00Z",
        "updated_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW"
      }
    ],
    "schema_version": "2.2.0",
    "selection_reason": "依据模拟岗位、授权范围、知识风险和确定性规则生成。",
    "status": "confirmed",
    "summary": "在统一基础内容后进入部门差异化路径，并前置高风险知识。",
    "target_department_names": [
      "炼钢生产部",
      "培训管理",
      "安全管理",
      "智信部"
    ],
    "title": "模拟候选方案 0001",
    "trace_id": "trc_01M04M0FTR37DSGT32ZS8Q9EFD",
    "training_goal_id": "goal_01M045GKG0YKARB9345NMT6ZDM",
    "updated_at": "2026-08-18T10:05:00Z",
    "updated_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW"
  },
  {
    "approval_id": null,
    "candidate_label": "候选 B · Agent 建议",
    "confidence": null,
    "course_ids": [
      "course_01M044J2Y023VMY1V94VNHSTNR",
      "course_01M044J2Y10Q50YCY7AWRAM8DV",
      "course_01M044J2Y2J1WWKKYBE4ZFSTGG"
    ],
    "courses": [
      {
        "completed": true,
        "department_name": "炼钢生产部",
        "duration_minutes": 20,
        "id": "course_01M044J2Y023VMY1V94VNHSTNR",
        "knowledge_point_ids": [
          "kp_01M042N1T0APS81540KBJJB9GF",
          "kp_01M042N1T1TS8PDWBQY7BTJN1H",
          "kp_01M042N1T2BXMMQ4E3KRKST5MF",
          "kp_01M042N1T34GQ3GK4CSQ57XV5B",
          "kp_01M042N1T41QJVRVC188STV0XP"
        ],
        "risk_level": "medium",
        "schema_version": "2.2.0",
        "title": "模拟课程 001：受控培训与风险边界"
      },
      {
        "completed": false,
        "department_name": "培训管理",
        "duration_minutes": 30,
        "id": "course_01M044J2Y10Q50YCY7AWRAM8DV",
        "knowledge_point_ids": [
          "kp_01M042N1T5AZ4HHPYJ41XHNXVR",
          "kp_01M042N1T6PKFX6FZHWYW5M6TN",
          "kp_01M042N1T7F0VJR4XXCPGVEENK",
          "kp_01M042N1T8GMDGYMEPT26WT6QM",
          "kp_01M042N1T9SRC3GFVT69FTC1JA"
        ],
        "risk_level": "high",
        "schema_version": "2.2.0",
        "title": "模拟课程 002：受控培训与风险边界"
      },
      {
        "completed": false,
        "department_name": "安全管理",
        "duration_minutes": 40,
        "id": "course_01M044J2Y2J1WWKKYBE4ZFSTGG",
        "knowledge_point_ids": [
          "kp_01M042N1TAAV1DMQFGF72FS2HF",
          "kp_01M042N1TB9QQK6TT3HMG3HS0D",
          "kp_01M042N1TCYQRSCQ2946A35XHV",
          "kp_01M042N1TDJZV44RNH3W4SZDAT",
          "kp_01M042N1TE005Y8BV8BP1SJBC7"
        ],
        "risk_level": "medium",
        "schema_version": "2.2.0",
        "title": "模拟课程 003：受控培训与风险边界"
      }
    ],
    "created_at": "2026-08-18T10:01:00Z",
    "created_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
    "entity_version": 1,
    "id": "plan_01M047DMM10WDYXV6ZW4QWA2PY",
    "idempotency_key": null,
    "knowledge_citation_ids": [
      "know_01M041PH80E4V8HF66N5YZ15VE",
      "know_01M041PH81FPGX0Z1HX3MC4QPR",
      "know_01M041PH8293AC5R0HCXN7JX43"
    ],
    "knowledge_citations": [
      {
        "authorized_scopes": [
          "training:read",
          "department:dept_01ARZ3NDEKTSV4RRFFQ69G5FAV"
        ],
        "confidence": null,
        "content_hash": "sha256:892a2bbba733f4441266c77a25b2a20f3c0fe179d664e2e90feead5981bbb9d0",
        "created_at": "2026-08-17T00:00:00Z",
        "created_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
        "document_name": "《生产区域基础行为模拟培训说明 01》",
        "document_version": "SIM-1.0.0-1",
        "entity_version": 1,
        "excerpt": "生产区域基础行为相关内容仅用于验证授权检索、引用和风险提示。",
        "id": "know_01M041PH80E4V8HF66N5YZ15VE",
        "idempotency_key": null,
        "metadata": {
          "dataset_version": "1.0.0",
          "profile": "small",
          "simulated": true
        },
        "relation": "支撑模拟培训方案、题目和测评关系校验。",
        "request_id": "req_01M04MVY50S3Z13SKATCKTCJ34",
        "retrieved_at": "2026-08-17T00:00:00Z",
        "risk_level": "medium",
        "schema_version": "2.2.0",
        "section": "模拟要求",
        "source_department_id": "dept_01ARZ3NDEKTSV4RRFFQ69G5FAV",
        "status": "effective",
        "trace_id": "trc_01M04KXDK0F26DJRFCSJR9X57B",
        "updated_at": "2026-08-17T00:05:00Z",
        "updated_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW"
      },
      {
        "authorized_scopes": [
          "training:read",
          "department:dept_01ARZ3NDEKTSV4RRFFQ69G5FAW"
        ],
        "confidence": null,
        "content_hash": "sha256:ef21f5819be63af3109ec2321156138a94a2a0d9867be35d780eff39e7e1be2f",
        "created_at": "2026-08-17T00:01:00Z",
        "created_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
        "document_name": "《高温区域进入前确认模拟培训说明 02》",
        "document_version": "SIM-1.0.0-1",
        "entity_version": 1,
        "excerpt": "高温区域进入前确认相关内容仅用于验证授权检索、引用和风险提示。",
        "id": "know_01M041PH81FPGX0Z1HX3MC4QPR",
        "idempotency_key": null,
        "metadata": {
          "dataset_version": "1.0.0",
          "profile": "small",
          "simulated": true
        },
        "relation": "支撑模拟培训方案、题目和测评关系校验。",
        "request_id": "req_01M04MVY5154PS3EBZFYW6BZK0",
        "retrieved_at": "2026-08-17T00:01:00Z",
        "risk_level": "high",
        "schema_version": "2.2.0",
        "section": "模拟要求",
        "source_department_id": "dept_01ARZ3NDEKTSV4RRFFQ69G5FAW",
        "status": "effective",
        "trace_id": "trc_01M04KXDK1RV3QHRJHC2RVDQ0K",
        "updated_at": "2026-08-17T00:06:00Z",
        "updated_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW"
      },
      {
        "authorized_scopes": [
          "training:read",
          "department:dept_01ARZ3NDEKTSV4RRFFQ69G5FAX"
        ],
        "confidence": null,
        "content_hash": "sha256:7e690dfb737dce3420d12cb7c1e2994fdacf46582d2a2cab816e28c9e8a6e2ee",
        "created_at": "2026-08-17T00:02:00Z",
        "created_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
        "document_name": "《设备联锁与隔离边界模拟培训说明 03》",
        "document_version": "SIM-1.0.0-1",
        "entity_version": 1,
        "excerpt": "设备联锁与隔离边界相关内容仅用于验证授权检索、引用和风险提示。",
        "id": "know_01M041PH8293AC5R0HCXN7JX43",
        "idempotency_key": null,
        "metadata": {
          "dataset_version": "1.0.0",
          "profile": "small",
          "simulated": true
        },
        "relation": "支撑模拟培训方案、题目和测评关系校验。",
        "request_id": "req_01M04MVY525CN94ZK3RRD6YM6A",
        "retrieved_at": "2026-08-17T00:02:00Z",
        "risk_level": "high",
        "schema_version": "2.2.0",
        "section": "模拟要求",
        "source_department_id": "dept_01ARZ3NDEKTSV4RRFFQ69G5FAX",
        "status": "effective",
        "trace_id": "trc_01M04KXDK2MDNF2C10DVXNEXQR",
        "updated_at": "2026-08-17T00:07:00Z",
        "updated_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW"
      }
    ],
    "metadata": {
      "dataset_version": "1.0.0",
      "profile": "small",
      "simulated": true
    },
    "request_id": "req_01M04MZ0CS8S1SV38QEED09MJB",
    "risk_level": "high",
    "rule_checks": [
      {
        "confidence": null,
        "created_at": "2026-08-18T08:21:00Z",
        "created_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
        "detail": "高风险正式下发等待人工审批。",
        "deterministic": true,
        "entity_version": 1,
        "id": "rule_01M048C561HG8AD223A2JNEM84",
        "idempotency_key": null,
        "label": "高风险动作审批",
        "metadata": {
          "dataset_version": "1.0.0",
          "profile": "small",
          "simulated": true
        },
        "request_id": "req_01M04MZ09NZ1AFFGMVAPZDJPR3",
        "risk_level": "high",
        "rule_code": "HIGH_RISK_APPROVAL_REQUIRED",
        "schema_version": "2.2.0",
        "status": "warning",
        "trace_id": "trc_01M04M0FQNN7A83284STGGM73Q",
        "updated_at": "2026-08-18T08:26:00Z",
        "updated_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW"
      }
    ],
    "schema_version": "2.2.0",
    "selection_reason": "依据模拟岗位、授权范围、知识风险和确定性规则生成。",
    "status": "candidate",
    "summary": "在统一基础内容后进入部门差异化路径，并前置高风险知识。",
    "target_department_names": [
      "炼钢生产部",
      "培训管理",
      "安全管理",
      "智信部"
    ],
    "title": "模拟候选方案 0002",
    "trace_id": "trc_01M04M0FTSD5TKA8YT5ZGKY0GN",
    "training_goal_id": "goal_01M045GKG0YKARB9345NMT6ZDM",
    "updated_at": "2026-08-18T10:06:00Z",
    "updated_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW"
  }
];

export const approvalRecord: ContractApproval = {
  "confidence": null,
  "created_at": "2026-08-18T13:20:00Z",
  "created_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
  "decided_at": null,
  "decision": null,
  "decision_comment": null,
  "entity_version": 1,
  "id": "approval_01M049ANR0CF7H24E47X21FD95",
  "idempotency_key": null,
  "impact_scope": [
    "department:dept_01ARZ3NDEKTSV4RRFFQ69G5FAV",
    "action:publish_training"
  ],
  "knowledge_citation_ids": [
    "know_01M041PH81FPGX0Z1HX3MC4QPR"
  ],
  "metadata": {
    "dataset_version": "1.0.0",
    "profile": "small",
    "simulated": true
  },
  "plan_id": "plan_01M047DMM10WDYXV6ZW4QWA2PY",
  "request_id": "req_01M04MZ0K0NF8NM6JBFZN4N4Z7",
  "requested_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
  "requested_changes": [],
  "reviewer_id": null,
  "reviewer_role_id": "role_01ARZ3NDEKTSV4RRFFQ69G5FAX",
  "risk_level": "high",
  "risk_summary": "包含模拟高风险知识，正式下发前必须由授权审核员决定。",
  "schema_version": "2.2.0",
  "status": "AP-WAITING",
  "submitted_at": "2026-08-18T13:20:00Z",
  "task_id": "task_01M046F420RT87AVTSH37F903B",
  "trace_id": "trc_01M04M0G10FB286AN09SVZRR0W",
  "updated_at": "2026-08-18T13:25:00Z",
  "updated_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW"
};

export const assessmentQuestions: ContractAssessmentQuestion[] = [
  {
    "confidence": null,
    "correct_option_indexes": [
      1
    ],
    "created_at": "2026-08-17T16:40:00Z",
    "created_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
    "entity_version": 1,
    "id": "question_01M043KJC0QBAMVKS6NXE6J899",
    "idempotency_key": null,
    "knowledge_point_id": "kp_01M042N1T1TS8PDWBQY7BTJN1H",
    "knowledge_point_name": "高温作业与设备联锁",
    "metadata": {
      "dataset_version": "1.0.0",
      "profile": "small",
      "simulated": true
    },
    "options": [
      "跳过风险检查",
      "确认授权、版本和必要输入",
      "使用真实员工资料",
      "直接形成绩效结论"
    ],
    "prompt": "关于“模拟知识点 002：高温区域进入前确认”，下列处理方式哪项符合模拟培训边界？",
    "question_type": "single",
    "request_id": "req_01M04MVZ48EBFEAYMK6TY7S6T8",
    "risk_level": "high",
    "schema_version": "2.2.0",
    "status": "active",
    "trace_id": "trc_01M04KXEJ8TYMJG6XYRHJ3MMCA",
    "updated_at": "2026-08-17T16:45:00Z",
    "updated_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW"
  },
  {
    "confidence": null,
    "correct_option_indexes": [
      0,
      1,
      2
    ],
    "created_at": "2026-08-17T16:41:00Z",
    "created_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
    "entity_version": 1,
    "id": "question_01M043KJC1N4B81A6TZAM6NR9F",
    "idempotency_key": null,
    "knowledge_point_id": "kp_01M042N1T0APS81540KBJJB9GF",
    "knowledge_point_name": "培训过程留痕",
    "metadata": {
      "dataset_version": "1.0.0",
      "profile": "small",
      "simulated": true
    },
    "options": [
      "核对授权范围",
      "确认资料版本",
      "保留可追溯摘要",
      "绕过审批直接写入"
    ],
    "prompt": "关于“模拟知识点 001：生产区域基础行为”，下列处理方式哪项符合模拟培训边界？",
    "question_type": "multiple",
    "request_id": "req_01M04MVZ49VRHP015TGE34A4TE",
    "risk_level": "medium",
    "schema_version": "2.2.0",
    "status": "active",
    "trace_id": "trc_01M04KXEJ9NS9V0W310P91PW22",
    "updated_at": "2026-08-17T16:46:00Z",
    "updated_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW"
  },
  {
    "confidence": null,
    "correct_option_indexes": [
      1
    ],
    "created_at": "2026-08-17T16:42:00Z",
    "created_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
    "entity_version": 1,
    "id": "question_01M043KJC255NTNK9RA30J42R8",
    "idempotency_key": null,
    "knowledge_point_id": "kp_01M042N1T2BXMMQ4E3KRKST5MF",
    "knowledge_point_name": "能力判断边界",
    "metadata": {
      "dataset_version": "1.0.0",
      "profile": "small",
      "simulated": true
    },
    "options": [
      "正确",
      "错误"
    ],
    "prompt": "关于“模拟知识点 003：设备联锁与隔离边界”，下列处理方式哪项符合模拟培训边界？",
    "question_type": "boolean",
    "request_id": "req_01M04MVZ4AB7MPF7JZTCT0198A",
    "risk_level": "high",
    "schema_version": "2.2.0",
    "status": "active",
    "trace_id": "trc_01M04KXEJA2MY0675QWF9ERW21",
    "updated_at": "2026-08-17T16:47:00Z",
    "updated_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW"
  }
];

export const agentRun: ContractAgentRun = {
  "confidence": null,
  "created_at": "2026-08-23T11:20:00Z",
  "created_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
  "current_stage": "模拟 Agent 流程",
  "decisions": [
    {
      "confidence": null,
      "created_at": "2026-08-23T14:40:00Z",
      "created_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
      "entity_version": 1,
      "evidence_ids": [
        "know_01M041PH81FPGX0Z1HX3MC4QPR"
      ],
      "id": "decision_01M04GYT80XKE9ND9MW8QH4PNA",
      "idempotency_key": null,
      "metadata": {
        "dataset_version": "1.0.0",
        "profile": "small",
        "simulated": true
      },
      "request_id": "req_01M04N586GH01ET7AYKWNNET1J",
      "risk_level": "medium",
      "run_id": "run_01M04F1S40VCRAWFDR55R14CBZ",
      "schema_version": "2.2.0",
      "source": "agent_suggestion",
      "status": "recorded",
      "summary": "区分 Agent 建议、确定性规则和人工决定，不暴露隐藏推理。",
      "title": "模拟 Agent 受控决策摘要",
      "trace_id": "trc_01M04M6QMGV2A9EE8M6GCVF4QF",
      "updated_at": "2026-08-23T14:45:00Z",
      "updated_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW"
    }
  ],
  "entity_version": 1,
  "id": "run_01M04F1S40VCRAWFDR55R14CBZ",
  "idempotency_key": null,
  "metadata": {
    "dataset_version": "1.0.0",
    "profile": "small",
    "simulated": true
  },
  "request_id": "req_01M04N580858S18K9HP3BJT357",
  "risk_level": "medium",
  "schema_version": "2.2.0",
  "state": {
    "checkpoint_id": "checkpoint_01M04HXATRXNTA6WWZZDC99QEC",
    "checkpoint_sequence": 4,
    "checkpointed_at": "2026-08-23T11:25:00Z",
    "completed_step_ids": [
      "step_01M04G09P0BCT24WTJM33VWWW9",
      "step_01M04G09P65HE131PAC7D6GGP6",
      "step_01M04G09PC9ND88H30H8ZSAZAV"
    ],
    "confidence": null,
    "constraints": [
      "高风险动作必须审批",
      "信息不足时暂停"
    ],
    "created_at": "2026-08-23T11:20:00Z",
    "created_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
    "current_approval_id": "approval_01M049ANR0CF7H24E47X21FD95",
    "current_assessment_result_id": "assessment_result_01M04B7PW0C5G5M80XM82EY9GS",
    "current_knowledge_citation_ids": [
      "know_01M041PH81FPGX0Z1HX3MC4QPR"
    ],
    "current_node": "ar-wait-input",
    "current_plan_id": "plan_01M047DMM10WDYXV6ZW4QWA2PY",
    "current_stage": "模拟 Agent 流程",
    "current_step_id": "step_01M04G09PJAVZA6P6P5GKVN8V3",
    "deadline": "2026-09-30",
    "entity_version": 1,
    "formal_write_occurred": false,
    "id": "run_01M04F1S40VCRAWFDR55R14CBZ",
    "idempotency_key": null,
    "last_error_code": null,
    "last_error_id": null,
    "metadata": {
      "dataset_version": "1.0.0",
      "profile": "small",
      "simulated": true
    },
    "next_allowed_actions": [
      "continue"
    ],
    "pending_step_ids": [
      "step_01M04G09PJAVZA6P6P5GKVN8V3"
    ],
    "recoverable": true,
    "request_id": "req_01M04N580858S18K9HP3BJT357",
    "retry_count": 0,
    "risk_level": "medium",
    "schema_version": "2.2.0",
    "started_at": "2026-08-23T11:20:00Z",
    "state_version": "1.0.0",
    "status": "AR-WAIT-INPUT",
    "target_employee_profile_ids": [
      "emp_01ARZ3NDEKTSV4RRFFQ69G5FAV"
    ],
    "task_id": "task_01M046F420RT87AVTSH37F903B",
    "trace_id": "trc_01M04M6QE8D6RM4DR5EN7XK7Y6",
    "training_goal_id": "goal_01M045GKG0YKARB9345NMT6ZDM",
    "updated_at": "2026-08-23T11:25:00Z",
    "updated_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
    "waiting_for": "authorized_user",
    "waiting_human_action": "补充模拟培训范围和截止日期。"
  },
  "status": "AR-WAIT-INPUT",
  "steps": [
    {
      "capability": "supervisor",
      "checkpoint_id": "checkpoint_01M04HXAT058K2490J5CBP1Y34",
      "confidence": null,
      "created_at": "2026-08-20T00:00:00Z",
      "created_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
      "decision_reason": "依据确定性规则选择继续、暂停、重试、回退或人工接管。",
      "entity_version": 1,
      "error_code": null,
      "finished_at": "2026-08-20T00:01:00Z",
      "id": "step_01M04G09P0BCT24WTJM33VWWW9",
      "idempotency_key": null,
      "input_summary": "授权范围内的模拟目标、知识引用和业务状态。",
      "label": "模拟 Agent 步骤 00001",
      "latency_ms": 20,
      "metadata": {
        "dataset_version": "1.0.0",
        "profile": "small",
        "simulated": true
      },
      "model_name": null,
      "output_summary": "形成不包含隐藏推理的模拟执行摘要。",
      "prompt_version": "simulated-c07-v1",
      "request_id": "req_01M04N5340GG9QDNWRMJ6RYBWC",
      "retry_count": 0,
      "risk_level": "medium",
      "run_id": "run_01M04F1S40VCRAWFDR55R14CBZ",
      "schema_version": "2.2.0",
      "skill_name": "simulated_deterministic_step",
      "started_at": "2026-08-20T00:00:00Z",
      "status": "succeeded",
      "token_count": 0,
      "trace_id": "trc_01M04M6JJ0RHBT19BF3JW8B3SH",
      "updated_at": "2026-08-20T00:05:00Z",
      "updated_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
      "writes_committed": false
    },
    {
      "capability": "skill",
      "checkpoint_id": "checkpoint_01M04HXAT6DVYYZ3YRQKA3ZY99",
      "confidence": null,
      "created_at": "2026-08-20T00:06:00Z",
      "created_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
      "decision_reason": "依据确定性规则选择继续、暂停、重试、回退或人工接管。",
      "entity_version": 1,
      "error_code": null,
      "finished_at": "2026-08-20T00:07:00Z",
      "id": "step_01M04G09P65HE131PAC7D6GGP6",
      "idempotency_key": null,
      "input_summary": "授权范围内的模拟目标、知识引用和业务状态。",
      "label": "模拟 Agent 步骤 00007",
      "latency_ms": 26,
      "metadata": {
        "dataset_version": "1.0.0",
        "profile": "small",
        "simulated": true
      },
      "model_name": null,
      "output_summary": "形成不包含隐藏推理的模拟执行摘要。",
      "prompt_version": "simulated-c07-v1",
      "request_id": "req_01M04N5346RQ2K6QS14DFTB86Q",
      "retry_count": 0,
      "risk_level": "medium",
      "run_id": "run_01M04F1S40VCRAWFDR55R14CBZ",
      "schema_version": "2.2.0",
      "skill_name": "simulated_deterministic_step",
      "started_at": "2026-08-20T00:06:00Z",
      "status": "waiting",
      "token_count": 0,
      "trace_id": "trc_01M04M6JJ6RY9QWFQTNMGCJQEB",
      "updated_at": "2026-08-20T00:11:00Z",
      "updated_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
      "writes_committed": false
    },
    {
      "capability": "planning",
      "checkpoint_id": "checkpoint_01M04HXATC1BQFH4TSJ6H5WG5W",
      "confidence": null,
      "created_at": "2026-08-20T00:12:00Z",
      "created_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
      "decision_reason": "依据确定性规则选择继续、暂停、重试、回退或人工接管。",
      "entity_version": 1,
      "error_code": null,
      "finished_at": "2026-08-20T00:13:00Z",
      "id": "step_01M04G09PC9ND88H30H8ZSAZAV",
      "idempotency_key": null,
      "input_summary": "授权范围内的模拟目标、知识引用和业务状态。",
      "label": "模拟 Agent 步骤 00013",
      "latency_ms": 32,
      "metadata": {
        "dataset_version": "1.0.0",
        "profile": "small",
        "simulated": true
      },
      "model_name": null,
      "output_summary": "形成不包含隐藏推理的模拟执行摘要。",
      "prompt_version": "simulated-c07-v1",
      "request_id": "req_01M04N534CXW569EQD9F6N56VQ",
      "retry_count": 0,
      "risk_level": "medium",
      "run_id": "run_01M04F1S40VCRAWFDR55R14CBZ",
      "schema_version": "2.2.0",
      "skill_name": "simulated_deterministic_step",
      "started_at": "2026-08-20T00:12:00Z",
      "status": "succeeded",
      "token_count": 0,
      "trace_id": "trc_01M04M6JJCZRY0F0E9ZCPX87HX",
      "updated_at": "2026-08-20T00:17:00Z",
      "updated_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
      "writes_committed": false
    },
    {
      "capability": "supervisor",
      "checkpoint_id": "checkpoint_01M04HXATJNXP095374Z3E1AX1",
      "confidence": null,
      "created_at": "2026-08-20T00:18:00Z",
      "created_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
      "decision_reason": "依据确定性规则选择继续、暂停、重试、回退或人工接管。",
      "entity_version": 1,
      "error_code": null,
      "finished_at": "2026-08-20T00:19:00Z",
      "id": "step_01M04G09PJAVZA6P6P5GKVN8V3",
      "idempotency_key": null,
      "input_summary": "授权范围内的模拟目标、知识引用和业务状态。",
      "label": "模拟 Agent 步骤 00019",
      "latency_ms": 38,
      "metadata": {
        "dataset_version": "1.0.0",
        "profile": "small",
        "simulated": true
      },
      "model_name": null,
      "output_summary": "形成不包含隐藏推理的模拟执行摘要。",
      "prompt_version": "simulated-c07-v1",
      "request_id": "req_01M04N534JTTG1HK2J094Y38X2",
      "retry_count": 0,
      "risk_level": "medium",
      "run_id": "run_01M04F1S40VCRAWFDR55R14CBZ",
      "schema_version": "2.2.0",
      "skill_name": "simulated_deterministic_step",
      "started_at": "2026-08-20T00:18:00Z",
      "status": "waiting",
      "token_count": 0,
      "trace_id": "trc_01M04M6JJJ14P0722T81MA4V7W",
      "updated_at": "2026-08-20T00:23:00Z",
      "updated_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW",
      "writes_committed": false
    }
  ],
  "task_id": "task_01M046F420RT87AVTSH37F903B",
  "trace_id": "trc_01M04M6QE8D6RM4DR5EN7XK7Y6",
  "updated_at": "2026-08-23T11:25:00Z",
  "updated_by": "usr_01ARZ3NDEKTSV4RRFFQ69G5FAW"
};

export const reportSummary: ContractReportSummary = {
  "assessment_pass_rate_percent": 78.0,
  "completion_rate_percent": 91.0,
  "disclaimer": "本页全部为模拟数据，仅用于验证流程、页面和交互，不代表真实企业培训效果。",
  "high_risk_intervention_count": 4,
  "reassessment_count": 4,
  "remedial_count": 4,
  "schema_version": "2.2.0",
  "status": "draft",
  "task_id": "task_01M046F420RT87AVTSH37F903B"
};

